### ISSUE TITLE
In UP state--> Saharanpur distt. -->Saharanpur sub. distt., Back function not working in Sharanpur distt. map. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#99]
check the screenshot,

![screenshot-github com-2018 12 18-12-32-19](https://user-images.githubusercontent.com/44860646/50137427-1f627280-02c1-11e9-8b4d-aedc5badaf14.png)

**Comment by guganbrandidea** [comment]
Fixed in local and not moved to the live server

**Comment by VigneshBI** [comment]
I checked in the live server but it is not fixed. Please change the status as fixed when you have moved into the server.
